### ISSUE TITLE
Installation on Steampunk

### ISSUE THREAD

**Issue by Xexer** [abap2UI5/abap2UI5-documentation#5]
Hello @oblomov-dev,
wanted to install the project to the ABAP Environment, but actually get an error:
![image](https://github.com/abap2UI5/abap2UI5-documentation/assets/58050124/f46ed79f-bdca-4664-a789-395803197dae)

The documentation for cloud is empty:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/01_installation/install_cloud.md

So I could not find a hint, how to solve it.

Thank you
Björn

**Comment by Xexer** [comment]
Checked the On-Premise installation, I have to use PREFIX mode, not FULL 👍

**Comment by oblomov-dev** [comment]
yes i will add a documentation soon, thank you for the hint.

**Comment by oblomov-dev** [comment]
updated the documentation and i close this issue now, just open a new one if you need further support.

https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/01_installation/install_cloud.md
